apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: e-commerce
  name: e-commerce
  namespace: e-commerce
spec:
  replicas: 5
  selector:
    matchLabels:
      app: e-commerce
  strategy: {}
  template:
    metadata:
      labels:
        app: e-commerce
    spec:
      containers:
        - image: soewailin/cake-e-commerce:v1.0.1
        name: e-commerce
        resources: {}
