apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: e-commerce
  name: e-commerce-svc
  namespace: e-commerce
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: e-commerce
  type: LoadBalancer
status:
  loadBalancer: {}

